color: null
fieldLayouts:
  5614f290-c2d1-4f14-b00a-e36916348ca0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-14T16:52:01+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4eb89cab-dfdb-41d2-84dc-7d0f3e878979
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: faad9abd-fb61-42b3-a695-f52bcfb52e14
        userCondition: null
handle: faqs
hasTitleField: true
icon: null
name: Faqs
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
