defaultPlacement: end
enableVersioning: true
entryTypes:
  - efcd8f45-b324-4db8-ab75-e28b60d5325e # News
handle: news
maxAuthors: 1
name: News
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  f585159c-4950-4889-a28d-c7271dae58a5: # cp-edit-showcase
    enabledByDefault: true
    hasUrls: true
    template: news/_entry.twig
    uriFormat: 'news/{slug}'
type: channel
