defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: efcd8f45-b324-4db8-ab75-e28b60d5325e # News
handle: news
maxAuthors: 1
name: News
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  ab499903-7a01-4d09-b0da-76a9b4f4385c: # DE
    enabledByDefault: true
    hasUrls: true
    template: _entry.twig
    uriFormat: 'neuigkeiten/{slug}'
  f585159c-4950-4889-a28d-c7271dae58a5: # EN
    enabledByDefault: true
    hasUrls: true
    template: _entry.twig
    uriFormat: 'news/{slug}'
type: channel
